const lorem = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  "Vestibulum pretium ex vitae dictum euismod. ",
  "Proin elementum ipsum in eros cursus, sit amet eleifend nulla vehicula. ",
  "Maecenas egestas facilisis laoreet. ",
  "Vivamus ipsum leo, condimentum at vestibulum id, luctus quis nulla. ",
  "Praesent luctus elementum nunc, sit amet bibendum magna hendrerit quis. ",
  "Aenean hendrerit porta vulputate. ",
  "Sed ullamcorper eros ut orci volutpat, quis euismod ante fringilla. ",
  "Nunc iaculis nibh in est placerat eleifend.\n\nPellentesque venenatis enim nec ipsum pharetra, sit amet pretium urna egestas. ",
  "Vestibulum convallis sapien vitae ornare euismod. ",
  "Integer elementum lectus nisl, ut facilisis lorem ullamcorper sed. ",
  "Mauris ultricies, purus eget interdum dapibus, odio elit porta risus, a ornare leo nisl et ex. ",
  "Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. ",
  "Donec tristique erat a lectus accumsan, nec pretium enim tincidunt. ",
  "Phasellus sit amet purus nec sapien molestie tincidunt non a nulla.\n\nNunc elementum est massa, in aliquet tellus auctor vitae. ",
  "Vestibulum et libero quam. ",
  "In a malesuada ex. ",
  "Integer nec euismod ligula. ",
  "Donec elementum odio quis fermentum viverra. ",
  "Quisque vestibulum velit id ex imperdiet posuere. ",
  "Aenean fringilla leo at dolor ullamcorper, imperdiet blandit massa aliquet. ",
  "Integer nisi urna, accumsan id pulvinar a, pulvinar vel magna. ",
  "Praesent ut commodo nulla. ",
  "Aliquam non eros magna. ",
  "Donec non orci mi. ",
  "Integer tristique felis sit amet tincidunt suscipit. ",
  "Mauris pellentesque augue nec nisi pretium, vitae fringilla tortor hendrerit. ",
  "Pellentesque ac consectetur eros.\n\nCurabitur quis nisl vel nunc sollicitudin hendrerit. ",
  "Ut magna ante, accumsan sit amet odio nec, imperdiet tempor risus. ",
  "Praesent efficitur feugiat nisi, ac semper arcu scelerisque et. ",
  "Donec vulputate id nulla quis facilisis. ",
  "Phasellus vitae semper mi, quis interdum ex. ",
  "Nunc velit elit, tincidunt at sollicitudin nec, viverra vel dolor. ",
  "Suspendisse vitae odio efficitur, vestibulum elit eget, pretium sem. ",
  "In nec commodo massa, vitae auctor nisl. ",
  "Curabitur gravida nulla vel diam tincidunt cursus. ",
  "Curabitur nibh nunc, hendrerit quis sodales non, commodo a ex. ",
  "Vestibulum in sem dui. ",
  "Vivamus vitae ipsum at risus sagittis posuere. ",
  "Nulla venenatis ligula ut tristique hendrerit. ",
  "Mauris volutpat molestie commodo.\n\nFusce vulputate malesuada sollicitudin. ",
  "Sed velit elit, finibus a ornare scelerisque, dignissim ac dolor. ",
  "Morbi quis elit urna. ",
  "Nulla in pharetra massa, at ornare lectus. ",
  "In id sapien vitae tellus rhoncus semper ut eu odio. ",
  "Pellentesque sit amet commodo nisl. ",
  "Sed efficitur metus quis blandit tincidunt. ",
  "Nulla suscipit venenatis hendrerit. ",
  "Donec luctus turpis vitae arcu tristique feugiat. ",
  "Donec mollis dapibus bibendum. ",
  "Sed mollis enim a tortor tempus maximus. ",
  "Phasellus tincidunt dui arcu, id cursus lectus placerat vitae. ",
  "Etiam vitae velit est.. "
]

export default function Lorem({ length = 1 }) {
  return <>{lorem.slice(0, length).join("")}</>;
}
